[package]
name = "village_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
bevy_prototype_debug_lines = "0.9.0"
ldtk_rust = "0.6.0"
pathfinding = "4.1.1"
rand = "0.8.5"
